HTTP请求
步骤一：浏览器首先向服务器发送http请求，请求包括：(Request Headers)
    方法：get还是post  get仅仅请求资源，post会附带用户数据
    路径：
    域名：
    其他相关的header
步骤二：服务器向浏览器响应第一次请求  (Response Headers)
    响应代码：200表示成功，3xx表示重定向，4xx表示客户端发送的请求有错误，5xx表示服务器端处理时发生了错误；
    响应类型：由Content-Type指定；
    以及其他相关的Header
步骤三：根据响应下来的源码去请求对应的数据(按需去拿)
***一个HTTP请求只处理一个资源
    例如：一个图片（img）  一个层叠样式表（css）..
步骤四。。。